# DO NOT CHANGE THIS
version: 0.0.1

#### DATABASE ####
mysql:
  host: "localhost"
  port: 3306
  database: "database"
  username: "username"
  password: "password"

maps:
  example:
    world: world_the_end
    spawn-positions:
      - x: 0
        y: 75
        z: 0
      - x: 5
        y: 75
        z: 0
      - x: 0
        y: 75
        z: 5
      - x: 5
        y: 75
        z: 5
    crate-locations:
      - x: 2
        y: 75
        z: 2
        tier: 1
      - x: 3
        y: 75
        z: 2
        tier: 2
      - x: 2
        y: 75
        z: 3
        tier: 2
      - x: 3
        y: 75
        z: 3
        tier: 1-3 # Chooses random tier between 1 and 3